Flattening nested arrays in NumPy can be done using a few different methods, depending on how deeply nested the array is and its structure.

🔁 If it's a proper NumPy array (regular shape):

* ✅ Example 1: Using flatten()
* ✅ Example 2: Using ravel() (returns a view when possible)
* ✅ Example 3: Using reshape(-1)

🧩 If it's an irregular (deeply nested or ragged) Python object array:
NumPy's built-in flattening won't work directly — you'll need to use a recursive method.

❌ Example 4: Deep nested list using np.array:
arr = np.array([[1, 2], [3, [4, 5]]], dtype=object)



🧠 Summary:
Structure	                    Method	                                    Notes
Regular 2D/3D NumPy array	    .flatten(), .ravel(), .reshape(-1)	        Efficient
Irregular/Python object	        Custom recursive flatten	                Slower but flexible


In [1]:
import numpy as np
# ✅ Example 1: Using flatten()
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
print(flat)                 # Output: [1 2 3 4]


# ✅ Example 2: Using ravel() (returns a view when possible)
flat = arr.ravel()
print(flat)                 # Output: [1 2 3 4]


# ✅ Example 3: Using reshape(-1)
flat = arr.reshape(-1)
print(flat)                 # Output: [1 2 3 4]

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


🧩 If it's an irregular (deeply nested or ragged) Python object array:
* NumPy's built-in flattening won't work directly — you'll need to use a recursive method. 

In [6]:
# ❌ Example 4: Deep nested list using np.array:
arr = np.array([[1, 2], [3, [4, 5]]], dtype=object)


# ✅ Custom flatten function (recursive)
def flatten_nested(arr):
    for item in arr:
        if isinstance(item, (list, np.ndarray)):
            yield from flatten_nested(item)
        else:
            yield item

nested = np.array([[1, 2], [3, [4, 5]]], dtype=object)
flat = np.array(list(flatten_nested(nested)))
print(flat)  # Output: [1 2 3 4 5]

[1 2 3 4 5]
