🔹 1. Accessing Elements in NumPy Arrays
✅ 1D Array
✅ 2D Array
✅ Slicing

In [1]:
# 1D array
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0], " ", arr[2])          # Output: 10  30

# ✅ 2D Array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d[1, 2])                  # Output: 6

# ✅ Slicing
print(arr[1:3])      # [20 30]
print(arr2d[:, 1])   # column: [2 5]
print(arr2d[0, :])   # row: [1 2 3]
print(arr2d[1:2, 1:3])


# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr1d[2])  

# Negative indexing
print("Negative indexing:", arr1d[-1])  

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Multidimensional array access
print("Multidimensional array access:", arr2d[1, 0])


10   30
6
[20 30]
[2 5]
[1 2 3]
[[5 6]]
Single element access: 30
Negative indexing: 50
Multidimensional array access: 4


🔹 2. Modifying Array Elements

In [3]:
arr[0] = 99
arr2d[1, 1] = 100
print(arr)          # [99, 20, 30, 40]
print(arr2d)        # [[1, 2, 3], [4, 100, 6]]

[99 20 30 40]
[[  1   2   3]
 [  4 100   6]]


🔹3. Deleting Elements

In [12]:
# ✅ Delete from 1D array
arr = np.array([1, 2, 3, 4, 5])
arr_new = np.delete(arr, 2)     # Deletes element at index 2
print(arr_new)                  # [1 2 4 5]


# ✅ Delete row/column from 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


# Delete 1st row
print(np.delete(arr2d, 0, axis=0))


# Delete 2nd column
print(np.delete(arr2d, 1, axis=1))

[1 2 4 5]
[[4 5 6]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


🔹 4. Inserting Elements

In [ ]:
# Insert in 1D
a = np.array([1, 2, 3])
new_a = np.insert(a, 1, 10)     # Insert 10 at index 1. 
print(new_a)                    # [1 10 2 3]

# Insert Element at last
print(np.insert(a,a.size,255))

# Insert in 2D
np.insert(arr2d, 1, [10, 11, 12], axis=0)       # Insert row
np.insert(arr2d, 1, [100, 101, 102], axis=1)    # Insert column

[ 1 10  2  3]
[  1   2   3 255]


array([[  1, 100,   2,   3],
       [  4, 101,   5,   6],
       [  7, 102,   8,   9]])

🔹 5. Appending Elements


In [6]:
import numpy as np
a = np.array([1, 2, 3])
a = np.append(a, [4, 5])
print(a)                    # [1 2 3 4 5]

# Append Row/Column in 2D
arr2d = [[1,2,3],[4,5,6]]
np.append(arr2d, [[10, 11, 12]], axis=0)            # Append row
# np.append(arr2d, [[100], [101], [102]], axis=1)     # Append column

[1 2 3 4 5]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

🔹 6. Reshaping Arrays


In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape((2, 3))
print(reshaped)
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


🔹 7. Copying Arrays

In [33]:
# ❌ Assignment (Reference)     - Shallow Copy (Same Reference...)
a = np.array([1, 2, 3])
b = a
b[0] = 99
print(a)  # [99 2 3]  (changes original)

# ✅ Deep Copy - Data is copied not reference. changes made in copy not affect the original data.
b = a.copy()
b[0] = 50
print(b)
print(a)  # [99 2 3]  (unchanged)


[99  2  3]
[50  2  3]
[99  2  3]


🔹 8. Stacking Arrays

In [9]:
# Vertical Stack
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))
# [[1 2]
#  [3 4]]


# Horizontal Stack
np.hstack((a, b))  # [1 2 3 4]

array([1, 2, 3, 4])

🔹 9. Splitting Arrays

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr, 3)        #Output [array([1, 2]), array([3, 4]), array([5, 6])]

# This will work only if we give exact numbers of variables as we making the split.
a, b = np.split(arr,2)
print(b)

[4 5 6]


🔹 10. Mathematical Operations


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)      # [5 7 9]
print(a * b)      # [4 10 18]
print(a ** 2)     # [1 4 9]
print(b - a)      # [3 3 3]

[5 7 9]
[ 4 10 18]
[1 4 9]
[3 3 3]


🔹 11. Mathematical Operations on elements

In [ ]:
n = np.array([1,2,3,4,5])
print(n[2]+n[3])        # 7 --> 3 + 4

7


🔹 12. Array Slicing

In [29]:
nn = np.array([1,2,3,4,5,6,7,8,9,10])

# Syntax - [Start: end: steps]

print(nn[0:3])  # [1,2,3] --> Elements on index 0, 1 and 2 ** 3 not included
print(nn[::2])  # Skip every 2nd element ** If not specified number automatically for start 0 taken for end size taken and for steps 0 taken
print(nn[::-1]) # Print array in reverse order
print(nn[::-2]) # Reverse order by skipping 2 digits.
print(nn[-3:-1])

[1 2 3]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]
[10  8  6  4  2]
[8 9]


In [4]:
#### Unary Operation: These operations are applied to each individual element in the array, without the need for multiple arrays (as in binary operations).


# Example array with both positive and negative values
arr22 = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value
result = np.absolute(arr22)
print("Absolute value:", result)

Absolute value: [3 1 0 1 3]
