In [2]:
import numpy as np

### set seed
A seed in NumPy (and other random libraries) is a starting value for the random number generator. Setting a seed (e.g., np.random.seed(123)) ensures that you get the same sequence of random numbers every time you run your code, making your results reproducible.

In [4]:
np.random.seed(123)

i = np.random.rand(5)
print(i)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]


### set random state which is independent from the global seed

In [5]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [4]:
# generate a random scalar
print(np.random.rand())      

0.6964691855978616


In [5]:
# generate a 1-D array
print(np.random.rand(3))           

[0.28613933 0.22685145 0.55131477]


In [6]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [7]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


### generate an array of random integers in a given interval [low, high)

In [ ]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 5, 'i8'))

# generate a 2-D array with specific size
size = (2, 3)
print(np.random.randint(1, 10, size, 'i8'))

[2 1 1 4 5]
[[1 1 5]
 [2 8 4]]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [ ]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.65472131 0.37380143 0.23451288 0.98799529 0.76599595 0.77700444
 0.02798196 0.17390652 0.15408224 0.07708648]
[0.8898657  0.7503787  0.69340324 0.51176338 0.46426806 0.56843069
 0.30254945 0.49730879 0.68326291 0.91669867]
[0.10892895 0.49549179 0.23283593 0.43686066 0.75154299 0.48089213
 0.79772841 0.28270293 0.43341824 0.00975735]
[0.34079598 0.68927201 0.86936929 0.26780382 0.45674792 0.26828131
 0.8370528  0.27051466 0.53006201 0.17537266]


### generate a random sample from a given 1-D array

In [ ]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
# The probabilities must sum to 1.0
# replace : boolean, optional Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.
# p : 1-D array-like, optional.  The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

probs = np.array([0.1, 0.8, 0.1, 0.7, 0.6])
probs = probs / probs.sum()
print(np.random.choice(range(5), 10, replace=True, p=probs))

[0.04347826 0.34782609 0.04347826 0.30434783 0.26086957]
[2 4 3 3 2 1 3 3 1 2]


In [ ]:
print(np.random.choice(100, 10))

[ 3 11  3 94  6  9 87 14 83 70]


In [15]:
print(np.random.choice([1,2,3], 10))

[2 2 2 3 1 3 3 2 3 3]


### shuffle an array in place

In [8]:
arr = np.array(range(12))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
np.random.shuffle(arr)
print(arr)

[ 3  4  0  9 10 11  1  6  8  7  2  5]


### generate a permutation of an array

In [12]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [8 0 1 7 3 4 9 5 6 2]
