In [1]:
import numpy as np

In [13]:
np.random.seed(321)
arr = np.random.randint(5,9,2)
print(arr)

[5 7]


### element-wise addition, subtraction, multiplication and division

In [14]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[15 17]
[-5 -3]
[50 70]
[0.5 0.7]


In [17]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [18]:
print(np.exp(arr))

[ 148.4131591  1096.63315843]


### element-wise logorithm

In [19]:
# natural log
print(np.log(arr))      

[1.60943791 1.94591015]


In [20]:
# base 2
print(np.log2(arr))     

[2.32192809 2.80735492]


In [21]:
# base 10
print(np.log10(arr))    

[0.69897    0.84509804]


### element-wise square root

In [22]:
print(np.sqrt(arr))

[2.23606798 2.64575131]


### element-wise sine and cosine

In [23]:
print(np.sin(arr))

[-0.95892427  0.6569866 ]


In [24]:
print(np.cos(arr))

[0.28366219 0.75390225]


### sum along a specified axis

In [37]:
# sum along the row
print(np.sum(arr, axis=0))    

12


In [40]:
# sum along the column
np.random.seed(321)
arr_2d = np.random.rand(3,2) * 10
print(arr_2d)
print(f'Sum along Columns : {np.sum(arr_2d, axis=1)}')  
print(f'Sum along Rows : {np.sum(arr_2d, axis=0)}')    

[[8.85947941 0.77912359]
 [9.79646157 2.47671458]
 [7.52884718 5.26675636]]
Sum along Columns : [ 9.638603   12.27317615 12.79560354]
Sum along Rows : [26.18478816  8.52259453]


### compute the min and max along a specified axis

In [41]:
# calculate min along the row
print(np.min(arr, axis=0))

5


In [43]:
# calculate max along the column
print(np.max(arr_2d, axis=1))    

[8.85947941 9.79646157 7.52884718]


In [44]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

7
5


### compute the indices of the min and max along a specified axis

In [48]:
# along the row
print(np.argmin(arr_2d, axis=0))
print(np.argmax(arr_2d, axis=0))

[2 0]
[1 2]


In [ ]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[1 4 3 3 4]
[3 3 0 2 3]


In [ ]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

24
8


### compute element-wise min and max of two arrays

In [49]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [ ]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.21779326 0.58882555 0.32195097 0.45853207 0.50994103 0.42358094
 0.32348379 0.31232886 0.16890174 0.49021443]
integral:  [0. 0. 5. 5. 5. 1. 2. 1. 6. 8.]


### compute the mean

In [ ]:
# compute the overall mean
print(np.mean(arr))

0.4810638752799312


In [ ]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.64961155 0.41447648 0.52911728 0.56593105 0.24618302]


In [ ]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.51636908 0.63275275 0.40130178 0.31527076 0.53962501]


### compute the median

In [50]:
# compute the overall median
print(np.median(arr))

6.0


In [51]:
# compute the median along the row
print(np.median(arr, axis=0)) 

6.0


In [53]:
# compute the median along the column
print(np.median(arr_2d, axis=1))

[4.8193015  6.13658808 6.39780177]


### compute the percentile

In [61]:
arr1 = np.random.rand(100)
arr2 = np.array(range(1,101))

print(arr2)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr2, [5, 65, 95, 99, 100]))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  5.95  65.35  95.05  99.01 100.  ]


### compute the standard deviation & variance

In [62]:
# compute the overall standard deviation
print(np.std(arr))

1.0


In [63]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

1.0


In [65]:
# compute the standard deviation along the column
print(np.std(arr_2d, axis=1))

[4.04017791 3.6598735  1.13104541]


In [67]:
# compute the overall variance
print(np.var(arr_2d))

10.809562831143367


In [68]:
# compute the variance along the row
print(np.var(arr_2d, axis=0))

[0.86562142 3.42277736]


In [69]:
# compute the variance along the column
print(np.var(arr_2d, axis=1))

[16.32303757 13.39467401  1.27926371]


### compute the covariance & correlation

In [75]:
arr = np.random.rand(2,3)

arr_1d = np.array([1,2,3,4,5])
print(arr)

[[0.27744533 0.67675425 0.79465709]
 [0.06474341 0.67925829 0.52664572]]


In [76]:
print(np.cov(arr))
print(np.cov(arr_1d))

[[0.07347612 0.07771485]
 [0.07771485 0.10237881]]
2.5


In [ ]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[1.         0.11028402]
 [0.11028402 1.        ]]


### compute cumulative sum & product

In [96]:
# calculate the cumulative sums along the row
size = (4,3)
np.random.seed(321)

arr_2d_int = np.random.randint(1,9,size,'i8')
print('Original Array : ')
print(arr_2d_int)

print('Cumulative sum Row Level : ')
print(np.cumsum( arr_2d_int, axis=0))

Original Array : 
[[5 3 5]
 [8 2 1]
 [2 1 3]
 [1 5 6]]
Cumulative sum Row Level : 
[[ 5  3  5]
 [13  5  6]
 [15  6  9]
 [16 11 15]]


In [98]:
# calculate the cumulative sums along the column
print(' Original Array : ')
print(arr_2d_int)
print(' Cumulative Sum along the Column : ')
print(np.cumsum(arr_2d_int, axis=1))    

 Original Array : 
[[5 3 5]
 [8 2 1]
 [2 1 3]
 [1 5 6]]
 Cumulative Sum along the Column : 
[[ 5  8 13]
 [ 8 10 11]
 [ 2  3  6]
 [ 1  6 12]]


In [102]:
# calculate the cumulative product along the row
print('Original Array : ')
print(arr_2d_int)

print('Cumulative product along the row')
print(np.cumprod(arr_2d_int, axis=0))   

Original Array : 
[[5 3 5]
 [8 2 1]
 [2 1 3]
 [1 5 6]]
Cumulative product along the row
[[ 5  3  5]
 [40  6  5]
 [80  6 15]
 [80 30 90]]


In [ ]:
# calculate the cumulative product along the column
print(np.cumprod(arr_2d_int, axis=1))  

[[ 5 15 75]
 [ 8 16 16]
 [ 2  2  6]
 [ 1  5 30]]


### element-wise comparison

In [105]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [111]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]
