In [1]:
import numpy as np

In [8]:
size = (3,3)
arr = np.random.randint(1, 9, size,'i8')

### sort an array along a specified axis

In [13]:
# sort along the row and return a copy
print('Sort along the row')
print(np.sort(arr, axis=0))   

# sort along the column and return a copy
print('Sort along the Columns : ')
print(np.sort(arr, axis=1)) 

# sort along the row and return the indices of the sorted elements
print('Sort along rows and return the indices : ')
print(np.argsort(arr, axis=0))  

# sort along the column and return the indices of the sorted elements
print('Sort along the column and return indices : ')
print(np.argsort(arr, axis=1))  

Sort along the row
[[1 2 1]
 [4 2 2]
 [5 6 6]]
Sort along the Columns : 
[[2 5 6]
 [2 4 6]
 [1 1 2]]
Sort along rows and return the indices : 
[[2 0 2]
 [1 2 1]
 [0 1 0]]
Sort along the column and return indices : 
[[1 0 2]
 [2 0 1]
 [0 2 1]]


In [14]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[1 2 1]
 [4 2 2]
 [5 6 6]]


In [15]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[1 1 2]
 [2 2 4]
 [5 6 6]]


In [16]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[1 1 2]
 [2 2 4]
 [5 6 6]]


### compute the indices that would sort an array along a specified axis

In [ ]:
arr = np.random.rand(5,5)

In [ ]:
# along the row
print(np.argsort(arr, axis=0))

[[1 1 2 2 0]
 [2 2 1 3 2]
 [0 4 0 1 4]
 [4 3 3 0 3]
 [3 0 4 4 1]]


In [ ]:
# along the column
print(np.argsort(arr, axis=1))

[[4 3 2 0 1]
 [0 3 1 2 4]
 [3 2 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]


In [ ]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[13 12  5 18  4  8  6  7 14  3 10 24  2 11  0 19 20 21  9 15 16 17 22  1
 23]
