In [1]:
import numpy as np

In [2]:
arr = np.random.rand(3,4)

### transpose an array

In [3]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.51844688 0.08678885 0.94256545]
 [0.29389732 0.26939532 0.70014402]
 [0.89692173 0.54365699 0.65564314]
 [0.6605094  0.40659126 0.96012849]]
[[0.51844688 0.08678885 0.94256545]
 [0.29389732 0.26939532 0.70014402]
 [0.89692173 0.54365699 0.65564314]
 [0.6605094  0.40659126 0.96012849]]
[[0.51844688 0.08678885 0.94256545]
 [0.29389732 0.26939532 0.70014402]
 [0.89692173 0.54365699 0.65564314]
 [0.6605094  0.40659126 0.96012849]]


### transpose of a high dimensional array with specified order of axes

In [4]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [5]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [ ]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.98440661, 0.15315942, 0.3330772 , 0.45128527, 0.95953312,
        0.01093673],
       [0.90659178, 0.99198992, 0.30401979, 0.59247041, 0.81129995,
        0.82223538]])

In [ ]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [ ]:
# return a copy
arr.flatten()    

array([0.98440661, 0.15315942, 0.3330772 , 0.45128527, 0.95953312,
       0.01093673, 0.90659178, 0.99198992, 0.30401979, 0.59247041,
       0.81129995, 0.82223538])

In [ ]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([0.98440661, 0.15315942, 0.3330772 , 0.45128527, 0.95953312,
       0.01093673, 0.90659178, 0.99198992, 0.30401979, 0.59247041,
       0.81129995, 0.82223538])

### append elements to an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [ ]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [ ]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [ ]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [ ]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [ ]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)