In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [4]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [5]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [7]:
# stack arrays vertically
cat = np.vstack((arr2, arr1))
print(cat)

[[5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [8]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### split an array 

In [9]:
arr = np.random.rand(6,6)

In [12]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.85696332, 0.18311835, 0.88786277, 0.04365013, 0.67571141,
        0.9052277 ],
       [0.38322309, 0.00703919, 0.65189914, 0.72462272, 0.22933418,
        0.73025597],
       [0.58693067, 0.32089611, 0.46107934, 0.60375129, 0.19216338,
        0.89974165]]), array([[0.44378671, 0.68814055, 0.78949297, 0.289885  , 0.22343906,
        0.44813895],
       [0.40848438, 0.17656147, 0.45650509, 0.45466792, 0.85879418,
        0.46724178],
       [0.22152082, 0.42753068, 0.20402668, 0.84079975, 0.03120949,
        0.57376147]])]


In [ ]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.18508467, 0.81993172, 0.18878547],
       [0.33688547, 0.1690414 , 0.3009311 ],
       [0.38885409, 0.03629261, 0.28913486],
       [0.02005274, 0.48136698, 0.61415211],
       [0.0788683 , 0.0391728 , 0.7366417 ],
       [0.03721661, 0.52077208, 0.57089404]]), array([[7.32790656e-01, 2.32967008e-01, 4.27668094e-01],
       [3.34405185e-01, 9.33827335e-05, 3.62887755e-01],
       [4.08424369e-02, 4.54621961e-01, 6.10321623e-02],
       [7.23370058e-01, 9.01568997e-01, 4.09904205e-01],
       [1.66363873e-01, 8.15416042e-01, 5.09941012e-01],
       [3.07035238e-01, 8.68276552e-01, 3.85862638e-02]])]
